#.travis.yml
language: node_js
node_js:
  - "10.15.0"
branches:
only:
  - master
before_script:
  - npm install -g firebase-tools
script:
  - npm run build 
  - npm run start 
after_success:
  - npm run test
  - firebase deploy --token $FIREBASE_TOKEN
notifications:
  email: skirep@gmail.com
  on_failure: always
  on_success: always